# Generated by Django 5.1.3 on 2024-12-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawn', '0002_rename_garden_lawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawn',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
