# Generated by Django 5.1.3 on 2024-12-06 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawn', '0004_userlawn'),
        ('plant', '0004_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawnProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawn.lawn')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant.product')),
            ],
        ),
    ]
