# Generated by Django 5.1.3 on 2024-12-06 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawn', '0005_lawnproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawn',
            name='user',
        ),
    ]
