# Generated by Django 5.1.3 on 2024-12-05 19:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_delete_region'),
        ('users', '0002_region_userregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRegion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plant.product')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.region')),
            ],
        ),
    ]
